sudo: required
language: java
jdk:
 - oraclejdk8

services:
  - docker

script: ./gradlew check

deploy:
  - provider: script
    script: ./gradlew publish
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+\.RELEASE$"